# Generated by Django 5.0.7 on 2024-07-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuser',
            name='count_of_buyer',
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_goods',
            field=models.IntegerField(null=True),
        ),
    ]
